### ISSUE TITLE
Improve Form Field Filling Performance Using Playwright

### ISSUE THREAD

**Issue by ArtemVinokhodov** [britka/playwrightium#68]
Hello!

Thank you for your Playwrightium project that integrates the capabilities of Selenide and Playwright for Java. It is an excellent solution that brings many benefits. However, I have encountered an issue where the speed of filling form fields has not increased compared to using pure Playwright.

In pure Playwright, the form filling process is significantly faster, which is an important aspect for many users, especially when working with large forms. It would be great if your solution could leverage Playwright's potential to speed up this process.

Please consider optimizing the code to enhance the form field filling speed. This improvement would make your project even more useful and efficient.

Thank you for your attention and effort!

Best regards,  
https://github.com/ArtemVinokhodov

**Comment by britka** [comment]
@ArtemVinokhodov 
I was able to reproduce this issue. I fixed `sendKeys` method. And now it works much faster.
But when you will use `Selenide.setValue` it will work slower. This is because  `Selenide.setValue` implementation. 
So if it is possible please use `PlaywrightiumWebelement.sendKeys` method.
